### PR TITLE
Add timer logging to dumps #32

### PR DESCRIPTION
**Pull request by hkir-dev**
Fix issue #32
Logging the start and end times of each rule to a log file. 
Can be [improved](https://stackoverflow.com/a/37725752) to log the execution duration. It is a small change (make every rule a single command) but it will reduce the readability I think.

### CODE REVIEW

**Review by Robbie1977 — APPROVED** [review]

**Review by Robbie1977 — CHANGES_REQUESTED** [review]
Can we just output the stage (as no indication which step) and the total time taken?

**Comment by dosumis** [comment]
> Can we just output the stage (as no indication which step) and the total time taken?

$@ = target name, so this will record each step being timed (think that's what you're asking)

**Review by dosumis — APPROVED** [review]

**Comment by hkir-dev** [comment]
Expected log will be something like:
```
remove_embargoed_data started: 1651061473
remove_embargoed_data ended: 1651061478
/out/dumps/owlery.owl started: 1651061478
/out/dumps/owlery.owl ended: 1651061479
...
```

**Comment by dosumis** [comment]
> Expected log will be something like:
> ```
> remove_embargoed_data started: 1651061473
> remove_embargoed_data ended: 1651061478
> /out/dumps/owlery.owl started: 1651061478
> /out/dumps/owlery.owl ended: 1651061479
> ...
> ```

I think that's fine and any improvements should be on a new PR.  

I guess it is harder to do this elegantly in Makefiles than in a shell script.  One possibility might be to use a make var set at the start and compare all timings back to the start time (with some nicer formatting of time).

**Review by Robbie1977 — APPROVED** [review]

**Pull request merged**
